apiVersion: v1
kind: ConfigMap
metadata:
  name: pentaho-config
data:
  PENTAHO_JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64
  DATABASE_HOST: 192.168.1.72
  DATABASE_PORT: "5432"
  DATABASE_NAME: rbpentaholog
  DATABASE_USER: pentaho
  DATABASE_PASSWORD: pentaho1234