apiVersion: v1
kind: Service
metadata:
  name: pentaho-service
spec:
  selector:
    app: pentaho-app
  ports:
    - protocol: TCP
      port: 2222
      targetPort: 31678  # Assuming the container's port is 31678
  type: ClusterIP